name: Android Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test and Build React
        run: |
          cd react
          echo "REACT_APP_CONQUEST_ACCESS_TOKEN=${{ secrets.REACT_APP_CONQUEST_ACCESS_TOKEN }}" >> .env
          echo "REACT_APP_CONQUEST_SERVER_URL=${{ secrets.REACT_APP_CONQUEST_SERVER_URL }}" >> .env
          yarn
          yarn test:all
          yarn build
      - name: Setup Cordova
        uses: oxr463/setup-cordova@0.0.3
        with:
          exec: |
            cordova platform add android && \
            cordova build --no-telemetry && \
            cp "$(find . -name '*.apk')" .
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ConquestApp
          path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
